version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      net_back:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      net_front:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      net_back:
        aliases:
          - post
      net_front:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      net_back:
        aliases:
          - comment
      net_front:
        aliases:
          - comment

volumes:
  post_db:

networks:
  net_back:
    external:
      name: reddit_net_back

  net_front:
    external:
      name: reddit_net_front

