kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: O/sv60YzZl5CEllae+yVmV/jhnn9l5aajvHURX3jpXc=
      - identity: {}
